// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ad_content_overpass.proto

package ad_content_overpass

import (
	ad_base_overpass "github.com/zbwang163/ad_base_overpass"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest_SearchType int32

const (
	SearchRequest_SEARCH_ALL     SearchRequest_SearchType = 0
	SearchRequest_SEARCH_ARTICLE SearchRequest_SearchType = 1
	SearchRequest_SEARCH_VIDEO   SearchRequest_SearchType = 2
	SearchRequest_SEARCH_IDEA    SearchRequest_SearchType = 3
	SearchRequest_SEARCH_ADVERT  SearchRequest_SearchType = 4
	SearchRequest_SEARCH_USER    SearchRequest_SearchType = 5
)

// Enum value maps for SearchRequest_SearchType.
var (
	SearchRequest_SearchType_name = map[int32]string{
		0: "SEARCH_ALL",
		1: "SEARCH_ARTICLE",
		2: "SEARCH_VIDEO",
		3: "SEARCH_IDEA",
		4: "SEARCH_ADVERT",
		5: "SEARCH_USER",
	}
	SearchRequest_SearchType_value = map[string]int32{
		"SEARCH_ALL":     0,
		"SEARCH_ARTICLE": 1,
		"SEARCH_VIDEO":   2,
		"SEARCH_IDEA":    3,
		"SEARCH_ADVERT":  4,
		"SEARCH_USER":    5,
	}
)

func (x SearchRequest_SearchType) Enum() *SearchRequest_SearchType {
	p := new(SearchRequest_SearchType)
	*p = x
	return p
}

func (x SearchRequest_SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchRequest_SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_ad_content_overpass_proto_enumTypes[0].Descriptor()
}

func (SearchRequest_SearchType) Type() protoreflect.EnumType {
	return &file_ad_content_overpass_proto_enumTypes[0]
}

func (x SearchRequest_SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchRequest_SearchType.Descriptor instead.
func (SearchRequest_SearchType) EnumDescriptor() ([]byte, []int) {
	return file_ad_content_overpass_proto_rawDescGZIP(), []int{1, 0}
}

type Case struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseId   string `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	CaseType int32  `protobuf:"varint,2,opt,name=case_type,json=caseType,proto3" json:"case_type,omitempty"`
}

func (x *Case) Reset() {
	*x = Case{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_content_overpass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_ad_content_overpass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_ad_content_overpass_proto_rawDescGZIP(), []int{0}
}

func (x *Case) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *Case) GetCaseType() int32 {
	if x != nil {
		return x.CaseType
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       string                        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit      string                        `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SearchType SearchRequest_SearchType      `protobuf:"varint,3,opt,name=search_type,json=searchType,proto3,enum=SearchRequest_SearchType" json:"search_type,omitempty"`
	QueryIds   []string                      `protobuf:"bytes,4,rep,name=query_ids,json=queryIds,proto3" json:"query_ids,omitempty"`
	Base       *ad_base_overpass.BaseRequest `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_content_overpass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_content_overpass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_ad_content_overpass_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *SearchRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

func (x *SearchRequest) GetSearchType() SearchRequest_SearchType {
	if x != nil {
		return x.SearchType
	}
	return SearchRequest_SEARCH_ALL
}

func (x *SearchRequest) GetQueryIds() []string {
	if x != nil {
		return x.QueryIds
	}
	return nil
}

func (x *SearchRequest) GetBase() *ad_base_overpass.BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *SearchResponse_SearchData     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Base *ad_base_overpass.BaseResponse `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_content_overpass_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_content_overpass_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_ad_content_overpass_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetData() *SearchResponse_SearchData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchResponse) GetBase() *ad_base_overpass.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type SearchResponse_SearchData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Docs       []*Case                      `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
	Pagination *ad_base_overpass.Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *SearchResponse_SearchData) Reset() {
	*x = SearchResponse_SearchData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_content_overpass_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse_SearchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_SearchData) ProtoMessage() {}

func (x *SearchResponse_SearchData) ProtoReflect() protoreflect.Message {
	mi := &file_ad_content_overpass_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_SearchData.ProtoReflect.Descriptor instead.
func (*SearchResponse_SearchData) Descriptor() ([]byte, []int) {
	return file_ad_content_overpass_proto_rawDescGZIP(), []int{2, 0}
}

func (x *SearchResponse_SearchData) GetDocs() []*Case {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *SearchResponse_SearchData) GetPagination() *ad_base_overpass.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_ad_content_overpass_proto protoreflect.FileDescriptor

var file_ad_content_overpass_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x76, 0x65,
	0x72, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x61, 0x64, 0x5f,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x22, 0xae, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x3a, 0x0a,
	0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x49, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0xff,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x77, 0x0a, 0x0a, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x45, 0x41, 0x52, 0x43,
	0x48, 0x5f, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x41, 0x52, 0x43,
	0x48, 0x5f, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x02, 0x12, 0x0f, 0x0a,
	0x0b, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x49, 0x44, 0x45, 0x41, 0x10, 0x03, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x41, 0x44, 0x56, 0x45, 0x52, 0x54, 0x10,
	0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x55, 0x53, 0x45, 0x52,
	0x10, 0x05, 0x22, 0xba, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0xff, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x54, 0x0a, 0x0a, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x6f, 0x63, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04, 0x64, 0x6f,
	0x63, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x32,
	0x3d, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2b, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0e, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a,
	0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x62, 0x77,
	0x61, 0x6e, 0x67, 0x31, 0x36, 0x33, 0x2f, 0x61, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x70, 0x61, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ad_content_overpass_proto_rawDescOnce sync.Once
	file_ad_content_overpass_proto_rawDescData = file_ad_content_overpass_proto_rawDesc
)

func file_ad_content_overpass_proto_rawDescGZIP() []byte {
	file_ad_content_overpass_proto_rawDescOnce.Do(func() {
		file_ad_content_overpass_proto_rawDescData = protoimpl.X.CompressGZIP(file_ad_content_overpass_proto_rawDescData)
	})
	return file_ad_content_overpass_proto_rawDescData
}

var file_ad_content_overpass_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ad_content_overpass_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ad_content_overpass_proto_goTypes = []interface{}{
	(SearchRequest_SearchType)(0),         // 0: SearchRequest.SearchType
	(*Case)(nil),                          // 1: Case
	(*SearchRequest)(nil),                 // 2: SearchRequest
	(*SearchResponse)(nil),                // 3: SearchResponse
	(*SearchResponse_SearchData)(nil),     // 4: SearchResponse.SearchData
	(*ad_base_overpass.BaseRequest)(nil),  // 5: BaseRequest
	(*ad_base_overpass.BaseResponse)(nil), // 6: BaseResponse
	(*ad_base_overpass.Pagination)(nil),   // 7: Pagination
}
var file_ad_content_overpass_proto_depIdxs = []int32{
	0, // 0: SearchRequest.search_type:type_name -> SearchRequest.SearchType
	5, // 1: SearchRequest.base:type_name -> BaseRequest
	4, // 2: SearchResponse.data:type_name -> SearchResponse.SearchData
	6, // 3: SearchResponse.base:type_name -> BaseResponse
	1, // 4: SearchResponse.SearchData.docs:type_name -> Case
	7, // 5: SearchResponse.SearchData.pagination:type_name -> Pagination
	2, // 6: ContentService.Search:input_type -> SearchRequest
	3, // 7: ContentService.Search:output_type -> SearchResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ad_content_overpass_proto_init() }
func file_ad_content_overpass_proto_init() {
	if File_ad_content_overpass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ad_content_overpass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Case); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_content_overpass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_content_overpass_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_content_overpass_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse_SearchData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ad_content_overpass_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ad_content_overpass_proto_goTypes,
		DependencyIndexes: file_ad_content_overpass_proto_depIdxs,
		EnumInfos:         file_ad_content_overpass_proto_enumTypes,
		MessageInfos:      file_ad_content_overpass_proto_msgTypes,
	}.Build()
	File_ad_content_overpass_proto = out.File
	file_ad_content_overpass_proto_rawDesc = nil
	file_ad_content_overpass_proto_goTypes = nil
	file_ad_content_overpass_proto_depIdxs = nil
}
